export const elements = [
    {
        id: 1,
        name: "Short Leg",
        color: 1,
        category: 1,
        width: 5.00,
        length: 5.00,
        depth: 20.00,
        stock_amount: 100,
        price: 10.00,
        installation_cost: 2.00,
        installation_time: { minutes: 30 },
    },
    {
        id: 2,
        name: "Long Leg",
        color: 2,
        category: 1,
        width: 5.00,
        length: 5.00,
        depth: 40.00,
        stock_amount: 50,
        price: 20.00,
        installation_cost: 3.00,
        installation_time: { minutes: 45 },
    },
    {
        id: 3,
        name: "Table Top",
        color: 3,
        category: 2,
        width: 100.00,
        length: 200.00,
        depth: 5.00,
        stock_amount: 20,
        price: 100.00,
        installation_cost: 10.00,
        installation_time: { hours: 1 },
    },
    {
        id: 4,
        name: "Frame",
        color: 1,
        category: 3,
        width: 50.00,
        length: 100.00,
        depth: 10.00,
        stock_amount: 30,
        price: 50.00,
        installation_cost: 5.00,
        installation_time: { minutes: 40 },
    },
    {
        id: 5,
        name: "Cabinet Door",
        color: 2,
        category: 2,
        width: 40.00,
        length: 60.00,
        depth: 2.00,
        stock_amount: 1,
        price: 25.00,
        installation_cost: 5.00,
        installation_time: { hours: 1 },
    }
];
